params:
  cuda_devices: [2,4]

optional_plugin_components:
 cuda_device_monitor:
   template: openfl.plugins.processing_units_monitor.pynvml_monitor.PynvmlCUDADeviceMonitor
   settings: []

shard_descriptor:
  template: superb_shard_descriptor.SuperbShardDescriptor
  params:
    rank_worldsize: 1, 10
